
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.*;
import java.util.Dictionary;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class bangla extends javax.swing.JFrame {

    /**
     * Creates new form bangla
     */
    public bangla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jButton10 = new javax.swing.JButton();
        jMenuItem2 = new javax.swing.JMenuItem();
        jFontChooser1 = new com.zfqjava.swing.JFontChooser();
        jFontChooser2 = new com.zfqjava.swing.JFontChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jButton10.setText("jButton10");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("বাংলা স্টীমার");
        setBackground(new java.awt.Color(153, 255, 153));
        setFont(new java.awt.Font("Siyam Rupali", 0, 48)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Siyam Rupali", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(jTextArea3);

        jButton3.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jButton3.setText("মুল শব্দ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        Font displayFont=new Font("Arial Unicode MS", Font.BOLD,14);
        jTextArea1.setFont(displayFont);
        jTextArea1.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jButton1.setText("মুছুন");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton4.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jButton4.setText("সন্ধি");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jButton5.setText("নাম");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jButton6.setText("উপসর্গ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jButton8.setText("একবচন");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jButton9.setText("গেম");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jButton7.setText("কাল");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jButton11.setText("পদ");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("jButton12");
        jButton12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton12MouseDragged(evt);
            }
        });
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jButton2.setText("অনুসর্গ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Siyam Rupali", 0, 11)); // NOI18N
        jButton13.setText("বাংলা বর্ণমালা");
        jButton13.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jButton13ComponentAdded(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jMenu1.setText("ফাইল");
        jMenu1.setFont(new java.awt.Font("Siyam Rupali", 0, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Siyam Rupali", 0, 12)); // NOI18N
        jMenuItem1.setText("সংরক্ষণ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setFont(new java.awt.Font("Siyam Rupali", 0, 12)); // NOI18N
        jMenuItem3.setText("ফাইল খুলুন");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("মুছুন");
        jMenu2.setFont(new java.awt.Font("Siyam Rupali", 0, 12)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem4.setFont(new java.awt.Font("Siyam Rupali", 0, 12)); // NOI18N
        jMenuItem4.setText("ইনপুট মুছুন");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Siyam Rupali", 0, 12)); // NOI18N
        jMenuItem5.setText("আউটপুট মুছুন");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Siyam Rupali", 0, 12)); // NOI18N
        jMenuItem6.setText("পুনরায়");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("হেল্প");
        jMenu3.setFont(new java.awt.Font("Siyam Rupali", 0, 12)); // NOI18N
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton11)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jButton8)
                                        .addComponent(jButton9))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5)
                                            .addComponent(jButton6)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton7))))
                            .addComponent(jButton13))
                        .addContainerGap(48, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton11, jButton13, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton12)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton11, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
            // TODO add your handling code here:
          Font displayFont=new Font("Siyam Rupali", Font.BOLD,14);
        String s = null;
        String s1 = null;
        String s2 = null;
       // int k = 0;
         InputStreamReader in=new InputStreamReader(System.in);
          BufferedReader br1=new BufferedReader(in);
           jTextArea3.setFont(displayFont); 
          jTextArea1.setFont(displayFont);
          jTextArea2.setFont(displayFont);
        s=jTextArea3.getText();
        MulShobdo mulshobdo=new MulShobdo(s);
        
        s2=mulshobdo.methodmulshobdo();
        jTextArea1.setText(s2);
     
    }//GEN-LAST:event_jButton3ActionPerformed
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(null);
        jTextArea3.setText(null);
        jTextArea2.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextArea3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea3AncestorAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
             Font displayFont=new Font("Siyam Rupali", Font.BOLD,14);
        String s = null;
        String s1 = null;
        String s2 = null;
        String s8=null;
       // int k = 0;
         InputStreamReader in=new InputStreamReader(System.in);
          BufferedReader br1=new BufferedReader(in);
           jTextArea3.setFont(displayFont); 
          jTextArea1.setFont(displayFont);
          jTextArea2.setFont(displayFont);
        s=jTextArea3.getText();
         Sondhi sondhi=new Sondhi(s);
        
        s2=sondhi.method1Sondhi();
        s8=sondhi.method2Sondhi();
        jTextArea1.setText(s2);
        jTextArea2.setText(s8);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
             Font displayFont=new Font("Siyam Rupali", Font.BOLD,14);
        String s = null;
        String s1 = null;
        String s2 = null;
       // int k = 0;
         InputStreamReader in=new InputStreamReader(System.in);
          BufferedReader br1=new BufferedReader(in);
           jTextArea3.setFont(displayFont); 
          jTextArea1.setFont(displayFont);
          jTextArea2.setFont(displayFont);
        s=jTextArea3.getText();
        Uposorgo kk=new Uposorgo(s);
        
        s2=kk.kkk();
        jTextArea1.setText(s2);
          
      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          Font displayFont=new Font("Siyam Rupali", Font.BOLD,14);
        String s = null;
        String s1 = null;
        String s2 = null;
       // int k = 0;
         InputStreamReader in=new InputStreamReader(System.in);
          BufferedReader br1=new BufferedReader(in);
           jTextArea3.setFont(displayFont); 
          jTextArea1.setFont(displayFont);
          jTextArea2.setFont(displayFont);
        s=jTextArea3.getText();
         Ekbochon ekbochon=new Ekbochon(s);
        
        s2=ekbochon.methodekbochon();
        jTextArea1.setText(s2);
          
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
     Font displayFont=new Font("Siyam Rupali", Font.BOLD,14);
           FileReader fr = null;
             String s = null;
                String s1=null;
                String s3=null;
                String s4=null;
                String s5=null;
                 char ch1,ch2,ch3,ch4;
                    int length=0,k=0,index=0,i,check=0;
                    String s6[]=new String[100];
        try {
            fr = new FileReader("game.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(bangla.class.getName()).log(Level.SEVERE, null, ex);
        }
              InputStreamReader in=new InputStreamReader(System.in);
               BufferedReader br=new BufferedReader(in); 
               BufferedReader br1=new BufferedReader(fr); 
                 jTextArea3.setFont(displayFont); 
          jTextArea1.setFont(displayFont);
          jTextArea2.setFont(displayFont);
        s4=jTextArea3.getText();
        s=s4;
        length=s.length();
        try {
            s1=br1.readLine();
        } catch (IOException ex) {
            Logger.getLogger(bangla.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(i=0;i<length;i++){
            try {
                s1=br1.readLine();
                if(String.valueOf(s.charAt(i)).indexOf(s1)==0)
                {
                    k=k+1;
                }
                if(String.valueOf(s.charAt(i)).indexOf(s1)!=0)
                {
                    break;
                }
            } catch (IOException ex) {
                Logger.getLogger(bangla.class.getName()).log(Level.SEVERE, null, ex);
            }
          
        }
          jTextArea1.setText(String.valueOf(k));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
           Font displayFont=new Font("Siyam Rupali", Font.BOLD,14);
           FileReader fr = null;
             String s = null;
                String s1=null;
                String s3=null;
                String s4=null;
                //String s5=null;
                 char ch1,ch2,ch3,ch4;
                    int length=0,k=0,index=0,i,check=0;
                    //String s6[]=new String[100];
        try {
            fr = new FileReader("game.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(bangla.class.getName()).log(Level.SEVERE, null, ex);
        }
              InputStreamReader in=new InputStreamReader(System.in);
               BufferedReader br=new BufferedReader(in); 
               BufferedReader br1=new BufferedReader(fr); 
                 jTextArea3.setFont(displayFont); 
          jTextArea1.setFont(displayFont);
          jTextArea2.setFont(displayFont);
        s4=jTextArea3.getText();
        s=s4;
      // String[]  s5={"সাথে","কাছে","থেকে"};
        String[] s6=s.split(" ");
         for(i=0;i<s6.length;i++)
        {
            
            if((s6[i].lastIndexOf("ের"))>0)
            {
               // if((s6[i+1].indexOf(s5))>=0){
                     index=s6[i].lastIndexOf("ের");
                     s3=s6[i].substring(0, index);
                     if(index>3){
                     jTextArea1.setText(s3);
                    break;
               }
            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
           Font displayFont=new Font("Siyam Rupali", Font.BOLD,14);
        String s = null;
        String s1 = null;
        String s2 = null;
       // int k = 0;
         InputStreamReader in=new InputStreamReader(System.in);
          BufferedReader br1=new BufferedReader(in);
           jTextArea3.setFont(displayFont); 
          jTextArea1.setFont(displayFont);
          jTextArea2.setFont(displayFont);
        s=jTextArea3.getText();
      Kal kal=new Kal(s);
      s2=kal.methodKal();
        jTextArea1.setText(s2);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
           Font displayFont=new Font("Siyam Rupali", Font.BOLD,14);
        String s = null;
        String s1 = null;
        String s2 = null;
       // int k = 0;
         InputStreamReader in=new InputStreamReader(System.in);
          BufferedReader br1=new BufferedReader(in);
           jTextArea3.setFont(displayFont); 
          jTextArea1.setFont(displayFont);
          jTextArea2.setFont(displayFont);
        s=jTextArea3.getText();
    Dic dictionary=new Dic(s) ;

       
    s2=dictionary.methodDic();
        jTextArea1.setText(s2);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        // TODO add your handling code here:
        this.setBackground(Color.yellow);
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseDragged
        // TODO add your handling code here:
       this.setBackground(Color.yellow);
    }//GEN-LAST:event_jButton12MouseDragged

    private void jButton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton11MouseEntered

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("icon.jpg"));

    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String fstring=null;
        fstring=jTextArea3.getText();
         try{
  // Create file 
  FileWriter fstream = new FileWriter("file.txt",true);
  BufferedWriter out = new BufferedWriter(fstream);
  out.write(fstring);
  //Close the output stream
  out.close();
  }catch (Exception e){//Catch exception if any
  System.err.println("Error: " + e.getMessage());
  }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
      FileChooser fileChooser = new FileChooser();
      fileChooser.setVisible(true);
      FileReader fr=null;
      
      String s1=null;
         try {
            //String s2=null;
            //s2=s;
              fr = new FileReader("file.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Kk.class.getName()).log(Level.SEVERE, null, ex);
        }
         BufferedReader br=new BufferedReader(fr); 
          int k=0;
        try{
            while((s1=br.readLine())!=null){
           jTextArea3.setText(s1+"\n");
            }
               
                  
    } catch (IOException ex) {
            Logger.getLogger(Kk.class.getName()).log(Level.SEVERE, null, ex);
        }
    //  fileChooser.setVisible(false); 
 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jTextArea3.setText(null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         jTextArea1.setText(null);
          jTextArea2.setText(null);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
             Font displayFont=new Font("Siyam Rupali", Font.BOLD,14);
        String s = null;
        String s1 = null;
        String s2 = null;
       // int k = 0;
         InputStreamReader in=new InputStreamReader(System.in);
          BufferedReader br1=new BufferedReader(in);
           jTextArea3.setFont(displayFont); 
          jTextArea1.setFont(displayFont);
          jTextArea2.setFont(displayFont);
        s=jTextArea3.getText();
     Pos pos=new Pos(s);
      s2=pos.methodPos();
        jTextArea1.setText(s2);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                     Font displayFont=new Font("Siyam Rupali", Font.BOLD,14);
        String s = null;
        String s1 = null;
        String s2 = null;
       int k = 0,i;
         InputStreamReader in=new InputStreamReader(System.in);
          BufferedReader br1=new BufferedReader(in);
           jTextArea3.setFont(displayFont); 
          jTextArea1.setFont(displayFont);
          jTextArea2.setFont(displayFont);
        s=jTextArea3.getText();
        String[] s6=s.split(" ");
        for(i=0;i<s6.length;i++){
     Onusorgo onusorgo=new Onusorgo(s6[i]);
   
      s2=onusorgo.methodOnusorgo();
      if(!s2.equals(" ")){
        jTextArea1.setText(jTextArea1.getText()+"\n"+s2);
      }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        BanglaBorno bangaBorno=new BanglaBorno();
        bangaBorno.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton13ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jButton13ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ComponentAdded
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bangla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bangla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bangla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bangla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new bangla().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.zfqjava.swing.JFontChooser jFontChooser1;
    private com.zfqjava.swing.JFontChooser jFontChooser2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
